// import Head from "next/head";
// import { Container, Heading } from "@chakra-ui/react";
// import axios from "axios";
// import { useEffect } from "react";

// export default function Home() {

//   const data = {
//     username: "john.doe",
//     password: "pass123",
//   }

//   // const fetchCourses = async () => {
//   //   try{
//   //     const coursesResponse = await axios.post("http://127.0.0.1:8000/api/login", data);
//   //     localStorage.setItem("token", coursesResponse.data.data.token);
//   //   }catch(err){
//   //     console.log(err);
//   //   }
//   // }

//   // useEffect(() => {
//   //   fetchCourses();
//   // }, [])

//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         <Container>
//           <Heading>Hello World</Heading>
//         </Container>
//       </main>
//     </>
//   );
// }
